name: Pipeline CI/CD TD Master

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:app

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: actions/checkout@v4

            - name: run tests
              run: ls -lah
