name: Pipeline CI/CD TD Master

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:app

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: actions/checkout@v4

            - name: run tests
              run: ls -lah
    build:
        name: build
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: build image
              run: docker build -t $IMAGE_NAME .
            - name: push image
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u